accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^confirm/(?P<activation_key>\w+)/', views.register_confirm, name="register_confirm"),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),

]

gameStore/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^allauth/', include('allauth.urls')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^games/$', views.browse_games, name="browse_games"),
    url(r'^games/my$', views.my_games, name="my_games"),
    url(r'^games/create/$', views.create_game, name="create_game"),
    url(r'^games/save/$', views.save_game, name="save_game"),
    url(r'^games/load/$', views.load_game, name="load_game"),
    url(r'^games/(?P<game_id>[0-9]+)/$', views.game, name="game"),
    url(r'^games/(?P<game_id>[0-9]+)/edit/$', views.edit_game, name="edit_game"),
    url(r'^games/(?P<game_id>[0-9]+)/delete/$', views.delete_game, name="delete_game"),
    url(r'^games/(?P<game_id>[0-9]+)/buy/$', views.payment_form, name="payment_form"),
    url(r'^games/(?P<game_id>[0-9]+)/r/$', views.payment_redirect, name="payment_redirect"),
    url(r'^games/(?P<category>[a-zA-Z]+)/$', views.browse_game_category, name='browse_game_category'),
    url(r'^highscores/$', views.browse_high_scores, name="high_scores"),
    url(r'^highscores/(?P<game_id>[0-9]+)/$', views.high_scores_for_game, name="high_scores_for_game"),
    url(r'^highscores/newScore/$', views.new_score, name="new_score"),
    url(r'^dashboard/$', views.developer_dashboard),
    url(r'^payment/$', views.payment_result, name="payment_result"),
    url(r'^', include('django.contrib.auth.urls')),
]

gameStore/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User, UserManager
import logging

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile')
    activation_key = models.CharField(max_length=40)
    key_expires = models.DateTimeField()


class GameCategory(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class Game(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    URL = models.URLField()
    image = models.URLField(default='http://placehold.it/150x80?text=IMAGE')
    description = models.CharField(max_length=2000, default="No description.")
    categories = models.ManyToManyField(GameCategory, related_name="games")
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    developer = models.ForeignKey('auth.User', related_name="developed_games")
    users = models.ManyToManyField(User, related_name="owned_games", default=None, blank=True)

    def __str__(self):
        return self.name


class Save(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name="saves", on_delete=models.CASCADE)
    game = models.ForeignKey(Game, related_name="saves", on_delete=models.CASCADE)
    game_state = models.CharField(max_length=255)


class Transaction(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    price = models.IntegerField()
    game = models.ForeignKey(Game)
    payer = models.ForeignKey(User, related_name="bought_transactions", on_delete=models.CASCADE)
    seller = models.ForeignKey(User, related_name="sold_transactions", on_delete=models.CASCADE)

    class Meta:
        get_latest_by = 'created_at'

    def calculate_payment_checksum(self):
        checksum_string = "pid={}&sid={}&amount={}&token={}".format(self.pk,
            settings.PAYMENT_SERVICE_SELLER_ID, self.price,
            settings.PAYMENT_SERVICE_SECRET_KEY)

        from hashlib import md5
        m = md5(checksum_string.encode("ascii"))
        return m.hexdigest()


class HighScore(models.Model):
    score = models.IntegerField()
    user = models.ForeignKey(User, related_name="scores", on_delete=models.CASCADE)
    game = models.ForeignKey(Game, related_name="scores", on_delete=models.CASCADE)

    def __str__(self):
        return self.game.name

gameStore/forms.py
from django.forms import ModelForm
from django import forms
from .models import Game


class GameForm(ModelForm):
    
    class Meta:
        model = Game
        fields = ['name', 'price', 'URL', 'categories', 'description', 'image', 'developer']
        widgets = {'developer': forms.HiddenInput()}

class PaymentForm(forms.Form):
    pid = forms.IntegerField(widget=forms.HiddenInput)
    sid = forms.CharField(widget=forms.HiddenInput)
    success_url = forms.URLField(widget=forms.HiddenInput)
    cancel_url = forms.URLField(widget=forms.HiddenInput)
    error_url = forms.URLField(widget=forms.HiddenInput)
    amount = forms.IntegerField(widget=forms.HiddenInput)
    checksum = forms.CharField(widget=forms.HiddenInput)

gameStore/views.py
from .models import Game, GameCategory, Transaction, HighScore, Save
from .forms import PaymentForm, GameForm
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponse
import json
from django.conf import settings
import logging

def game(request, game_id):
    """
    View for a specific game. Description is accessible to all users, but
    only users who have bought the game and the developer should be able to
    access the actual game.
    """
    game = get_object_or_404(Game, pk=game_id)
    bought_game = False
    is_developer = False
    developed_game = False
    if request.user.is_authenticated():
        bought_game = request.user.owned_games.filter(pk=game.pk).exists()
        developed_game = request.user.developed_games.filter(pk=game.pk).exists()
        is_developer = request.user.groups.filter(name='Developer').exists()

    return render(request, 'game.html', {'user': request.user, 'game': game,
    'developed_game': developed_game, 'bought_game': bought_game,
    'is_developer': is_developer})


@login_required
def new_score(request):
    current_user = request.user
    current_game = Game.objects.get(name=request.POST.get('game'))
    if request.is_ajax():
        score = HighScore.objects.create(score=request.POST.get('score'), user=current_user, game=current_game)
        return HttpResponse("Success")


@login_required
def save_game(request):
    current_user = request.user
    current_game = Game.objects.get(name=request.POST.get('game'))
    if request.is_ajax():
        save = Save.objects.create(game_state=request.POST.get('state'), user=current_user, game=current_game)
        return HttpResponse("Success")


@login_required
def load_game(request):
    current_user = request.user
    current_game = Game.objects.get(name=request.GET['game'])
    if request.is_ajax():
        saves = Save.objects.filter(user=current_user, game=current_game).order_by('-created_at')
        if saves:
            data = {'found': 1, 'state': saves.first().game_state}
            json_data = json.dumps(data)
            return HttpResponse(json_data)
        else:
            data = {'found': 0}
            json_data = json.dumps(data)
            return HttpResponse(json_data)


@login_required
def create_game(request):
    """
    View for adding new games to the service. Either renders a form for adding
    a new game or processes a submitted one. Accessible only to users within
    the developer group.
    """
    is_developer = request.user.groups.filter(name='Developer').exists()
    # if this is a POST request we need to process the form data
    if is_developer:
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            # check whether it's valid:
            form = GameForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/games/')
            else:
                return HttpResponse(status=400)

        # if a GET (or any other method) we'll create a blank form
        else:
            form = GameForm(initial={'developer': request.user})

        return render(request, 'create_game.html', {'form': form, 'is_developer': is_developer})
    else:
        return HttpResponseForbidden()

@login_required
def edit_game(request, game_id):
    """
    View for editing a given game after adding. Only accessible for the developer
    that originally created the game.
    """

    game = get_object_or_404(Game, pk=game_id)
    user_developed_this_game = request.user == game.developer

    if user_developed_this_game:
        if request.method == 'POST':
            form = GameForm(request.POST, instance=game)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/games/')
            else:
                return HttpResponse(status=400)

        else:
            form = GameForm(initial={'developer': game.developer, 'name': game.name,
                'price': game.price, 'URL': game.URL,
                'description': game.description, 'image': game.image})

        return render(request, 'edit_game.html', {'form': form,
            'user_developed_this_game': user_developed_this_game, 'game': game})
    else:
        return HttpResponseForbidden()

@login_required
def delete_game(request, game_id):
    """
    Deletes a specific game. Only accessible to developer that originally
    created the game.
    """
    game = get_object_or_404(Game, pk=game_id)
    user_developed_this_game = request.user == game.developer

    if user_developed_this_game:
        if request.method == 'POST':
            game.delete()
            return HttpResponseRedirect('/games/')
        else:
            return render(request, 'game_confirm_delete.html')
    else:
        return HttpResponseForbidden()

def browse_games(request):
    """
    Listing of all available games. Accessible also to unauthenticated users.
    """

    categories = GameCategory.objects.all()
    cheapest = Game.objects.all().order_by('-price').first()
    is_developer = request.user.groups.filter(name='Developer').exists()
    games = Game.objects.all()
    recent_games = Game.objects.all().order_by('-created')[:4]

    return render(request, 'browse_games.html', {'games': games,
                                                 'categories': categories, 'recent': recent_games, 'cheapest': cheapest})


def browse_game_category(request, category):
    """
    Browse games in a given category. Accessible also to unauthenticated users.
    """
    category = get_object_or_404(GameCategory, name=category.lower())
    games = Game.objects.filter(categories=category)

    return render(request, 'browse_game_category.html', {'games': games,
    'category': category})


@login_required
def my_games(request):
    """
    List games bought by and accessible to a single user.
    """
    is_developer = request.user.groups.filter(name='Developer').exists()
    if is_developer:
        return redirect(developer_dashboard)

    games = request.user.owned_games

    return render(request, 'my_games.html', {'user': request.user, 'games': games})


def browse_high_scores(request):
    """
    Listing of all high scores of all games. Accessible to all users.
    """
    high_scores = HighScore.objects.all()
    games = Game.objects.all()

    return render(request, 'browse_high_scores.html', {'high_scores': high_scores,
    'games': games})

def high_scores_for_game(request, game_id):
    """
    Listing of all high scores for a given game. Accessible to all users.
    """
    current_game = get_object_or_404(Game, pk=game_id)
    high_scores = HighScore.objects.all().filter(game=current_game)

    return render(request, 'high_scores_for_game.html', {'high_scores': high_scores, 'game': current_game})


@login_required
def payment_form(request, game_id):
    """
    Confirmation view for buying a game.
    """
    game = get_object_or_404(Game, pk=game_id)

    return render(request, 'payment_form.html', {'game': game})


@login_required
def payment_redirect(request, game_id):
    """
    Needed to create transaction in our system and to pass values to payment
    service when a user buys a given game.
    """
    game = get_object_or_404(Game, pk=game_id)
    owns_game = request.user.owned_games.filter(pk=game.pk)
    if owns_game:
        return redirect('game', game_id)
    else:
        transaction = Transaction.objects.create(game=game, price=game.price,
            payer=request.user, seller=game.developer)

        checksum = transaction.calculate_payment_checksum()

        form = PaymentForm(initial={'pid': transaction.pk, 'checksum': checksum,
            'amount': game.price, 'sid': settings.PAYMENT_SERVICE_SELLER_ID,
            'success_url': settings.PAYMENT_RESULT_URL,
            'cancel_url': settings.PAYMENT_RESULT_URL,
            'error_url': settings.PAYMENT_RESULT_URL})

        return render(request, 'payment_redirect.html', {'form': form})


def payment_result(request):
    """
    A view for handling user rights to a bought game after redirected from
    payment service.
    """
    result = request.GET['result']
    pid = request.GET['pid']
    ref = request.GET['ref']
    request_checksum = request.GET['checksum']

    #Ensure checksum is correct.
    checksum_string = "pid={}&ref={}&result={}&token={}".format(pid,
        ref, result, settings.PAYMENT_SERVICE_SECRET_KEY)

    from hashlib import md5
    calculated_checksum = md5(checksum_string.encode("ascii")).hexdigest()

    if result == 'success' and calculated_checksum == request_checksum:
        success = True
        transaction = get_object_or_404(Transaction, pk=pid)
        transaction.payer.owned_games.add(transaction.game)
    else:
        Transaction.objects.get(pk=pid).delete()
        success = False

    return render(request, 'payment_result.html', {'success': success})


def index(request):
    is_developer = request.user.groups.filter(name='Developer').exists()
    if is_developer:
        return redirect(developer_dashboard)
    elif request.user.is_authenticated():
        return redirect(my_games)
    else:
        return render(request, 'index.html')


@login_required
def developer_dashboard(request):
    """
    Default view for developers to manage their games.
    """
    is_developer = request.user.groups.filter(name='Developer').exists()

    if is_developer:
        return render(request, 'developer_dashboard.html', {'user': request.user,
                                                            'transactions': request.user.sold_transactions, 'games': request.user.developed_games})
    else:
        return HttpResponseForbidden()

gameStore/templates/browse_game_category.html
{% extends "layout.html" %}
{% block title %}Browse {{ tcategory.name }} games{% endblock %}
{% block content %}
    <div class="intro-header">
        <h1>Browse {{ category }} games</h1>
        <hr class="intro-divider"><br>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            {% for game in games.all %}
                    <div class="col-sm-4 col-lg-4 col-md-4" onclick="location.href='{% url "game" game_id=game.pk %}'">
                        <div class="thumbnail">
                            <img src="{{ game.image }}" alt="">
                            <div class="caption">
                                <h4 class="pull-right">${{ game.price }}</h4>
                                <h4><a href="#">{{ game.name }}</a>
                                </h4>
                                <p>{{ game.description }}</p>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </div>
    <!-- /.container -->

{% endblock %}

gameStore/templates/browse_games.html
{% extends "layout.html" %}
{% block title %}Browse Games{% endblock %}
{% block content %}
    <div class="intro-header">
        <h1>Browse games</h1>
        <hr class="intro-divider"><br>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <p class="lead">Categories</p>
                <div class="list-group">
                    {% for category in categories %}
                        <a class="list-group-item" href="{% url 'browse_game_category' category.name %}">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-9">
                <p class="lead">Featured games</p>
                <div class="row carousel-holder">
                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="4"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <a href='#'>
                                        <img onclick="location.href='{% url "game" game_id=cheapest.pk %}'"
                                             class="slide-image" src="{{ cheapest.image }}" alt="">
                                    </a>
                                </div>
                                {% for game in recent %}
                                    <div class="item">
                                        <img onclick="location.href='{% url "game" game_id=game.pk %}'"
                                             class="slide-image" src="{{ game.image }}" alt="">
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <p class="lead">All games</p>
                    {% for game in games %}
                    <div class="col-sm-4 col-lg-4 col-md-4" onclick="location.href='{% url "game" game_id=game.pk %}'">
                        <div class="thumbnail thumbnail-item">
                            <img src="{{ game.image }}" alt="">
                            <div class="caption">
                                <h4>{{ game.name }}</h4>
                                <p>{{ game.description }}</p>
                                <h4 class="">${{ game.price }}</h4>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
    </div>

{% endblock %}

gameStore/templates/browse_high_scores.html
{% extends "layout.html" %}
{% block title %}Browse Games{% endblock %}
{% block content %}
        <div class="intro-header">
        <h1>Browse high scores:</h1>
        <hr class="intro-divider"><br>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            {% for game in games.all %}
                <div class="col-sm-3"
                     onclick="location.href='{% url 'high_scores_for_game' game_id=game.pk %}'">
                    <div class="thumbnail thumbnail-item">
                        <img src="{{ game.image }}" alt="">
                        <div class="caption highscores">
                            <h4>{{ game.name }}</h4>
                                {% for high_score in high_scores %}
                                    {% if high_score.game_id == game.pk %}
                                        <h5>{{ forloop.counter }} . {{ high_score.user.username }} - {{ high_score.score }}</h5>
                                    {% endif %}
                                {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
    <!-- /.container -->
{% endblock %}

gameStore/templates/create_game.html
{% extends "layout.html" %}
{% block title %} Add new game {% endblock %}
{% block content %}
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <div class="container">
                        <div class="col-md-4 col-md-offset-4">
                         {% if is_developer %}
                            <h3>Add game to database</h3><br>
                            <form class="" method="post" action="/games/create/">{% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group">
                                        <label class="control-label">{{ field.label }}</label>
                                        <div class="controls">
                                            {{ field }}
                                        </div>
                                    </div>
                                {% endfor %}<br>
                                <input class="btn btn-lg btn-primary btn-block" type="submit" value="Add game" />
                            </form>
                         {% else %}
                             <p>Your are not authorized for this page.</p>
                         {% endif %}
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container -->
    </div>
    <!-- /.intro-header -->

{% endblock %}

gameStore/templates/developer_dashboard.html
{% extends "layout.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
    <div class="intro-header">
        <h1>Dashboard</h1>
        <hr class="intro-divider"><br>

    <div class="row">
        <div class="col-md-4 col-md-offset-1">
            <h4>Statistics</h4><br>
                How many games bought
                 How much money I have made
                Tämä vois olla vain ylhäällä koko sivun levyinen. Ei välttämättä tarvi omaa
                columnia. Joku hieno graafi vielä tähän.
        </div>
    <div class="col-md-3">
        <h4 class="">Transactions</h4><br>
     <table class="table table-bordered table-hover table-striped">
         <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Game</th>
                <th>Amount</th>
            </tr>
         </thead>
         <tbody>
            {% for transaction in transactions.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ transaction.created_at }}</td>
                    <td>{{ transaction.game }}</td>
                    <td>{{ transaction.price }}</td>
                </tr>
            {% endfor %}

         </tbody>
     </table>
    </div>
    <div class="col-md-3">
        <h4>My Games</h4><br>
            <div>
                <h5><a class="btn btn-lg btn-primary btn-block" href="{% url 'create_game' %}">Add a new game</a></h5><br>
                {% for game in games.all %}
                        <div class="thumbnail thumbnail-item" onclick="location.href='{% url "game" game_id=game.pk %}'">
                            <div class="caption">
                                <h4>{{ game.name }}</h4>
                                <p>{{ game.description }}</p>
                            </div>
                        </div>
                {% endfor %}

            </div>
        </div>
    </div>
    </div>
{% endblock %}

gameStore/templates/edit_game.html
{% extends "layout.html" %}
{% block title %} Edit game {% endblock %}
{% block content %}
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <div class="container">
                        <div class="col-md-4 col-md-offset-4">
                         {% if user_developed_this_game %}
                            <h3>Edit game</h3><br>
                            <form class="" method="post" action="/games/{{ game.pk }}/edit/">{% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group">
                                        <label class="control-label">{{ field.label }}</label>
                                        <div class="controls">
                                            {{ field }}
                                        </div>
                                    </div>
                                {% endfor %}<br>
                                <input class="btn btn-lg btn-primary btn-block" type="submit" value="Save" />
                            </form>
                            <a href="{% url 'delete_game' game_id=game.pk %}">Delete game</a>
                         {% else %}
                             <p>Your are not authorized for this page.</p>
                         {% endif %}
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container -->
    </div>
    <!-- /.intro-header -->

{% endblock %}

gameStore/templates/index.html
{% extends "layout.html" %}
{% block title %} Welcome to the gameStore!{% endblock %}
{% block content %}
    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>GameStore</h1>
                        <h3>The home of gamers all around the world.</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="{% url "accounts:user_login" %}" class="btn btn-default btn-lg"><span class="network-name"> Log in </span></a>
                            </li>
                            <li>
                                <a href="{% url "accounts:register" %}" class="btn btn-default btn-lg"> <span class="network-name">Register</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container -->
    </div>
    <!-- /.intro-header -->

{% endblock %}

gameStore/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'gameStore/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'gameStore/css/layout.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'gameStore/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="{% url 'index' %}">Home</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'browse_games' %}">Browse Games</a></li>
                        <li><a href="{% url 'high_scores' %}">Highscores</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'accounts:user_logout' %}">Log out</a></li>
                        </ul>
                    {% else %}
                        <li><a href="{% url 'browse_games' %}">Browse Games</a></li>
                        <li><a href="{% url 'high_scores' %}">Highscores</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'accounts:register' %}">Register</a></li>
                            <li><a href="{% url 'accounts:user_login' %}">Log in</a></li>
                        </ul>
                    {% endif %}
            </div>
        </div>
    </nav>

    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Back to top</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Juho Heikkilä, Mikko Karjalainen and Lauri Eurén - 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'gameStore/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'gameStore/js/bootstrap.min.js' %}"></script>


</body>
</html>

gameStore/templates/payment_redirect.html
<html>
    <body onload="document.my_form.submit()">
        You should be automatically redirected to your payment provider. If not,
        click "Accept payment.".
        <form action="http://payments.webcourse.niksula.hut.fi/pay/" name="my_form" method="POST">
          {{ form }}
          <input type="submit" value="Accept Payment"/>
        </form>
    </body>
</html>